name : my-github-action
on : [push]
jobs :
       Runs-bats :
                   runs-on : ubuntu-latest
                   steps :
                     - uses : actions/checkout@v3
                     - name : test_env
                       run : echo $my_name && env
                       env:
                         my_name : dataloord
                     - name : Give_permission to execute
                       run : chmod +x ./.github/scripts/sample.sh
                     - name : run_script
                       run : source ./.github/scripts/sample.sh
                     - name : see job context
                       run : echo '${{ toJSON(job) }}'
                     - name : set up expressions
                       run : echo '${{ toJSON(github) }}'
                       if : contains(fromJSON('["shu", "chan"]'),'shu')
                     - run : env                
